/* Generated By:JavaCC: Do not edit this line. SQLParserTreeConstants.java Version 5.0 */
package sqlParser;

public interface SQLParserTreeConstants
{
    public int JJTSTART = 0;
    public int JJTEXPRESSION = 1;
    public int JJTQUERY = 2;
    public int JJTSFW = 3;
    public int JJTSELLIST = 4;
    public int JJTFROMLIST = 5;
    public int JJTCONDITION = 6;
    public int JJTTUPLE = 7;
    public int JJTCRET = 8;
    public int JJTCOLLIST = 9;
    public int JJTTYPE = 10;
    public int JJTTAB_CONSTRAINT = 11;
    public int JJTDROPT = 12;
    public int JJTDELT = 13;
    public int JJTINST = 14;
    public int JJTINLIST = 15;
    public int JJTVLIST = 16;
    public int JJTUPDT = 17;
    public int JJTUPLIST = 18;
    public int JJTATTRIBUTE = 19;
    public int JJTRELATION = 20;
    public int JJTPATTERN = 21;
    public int JJTNUMBER = 22;
    public int JJTIDENTIFIER = 23;


    public String[] jjtNodeName = {
            "Start",
            "Expression",
            "Query",
            "SFW",
            "SelList",
            "FromList",
            "Condition",
            "Tuple",
            "CreT",
            "ColList",
            "Type",
            "Tab_constraint",
            "DropT",
            "DelT",
            "InsT",
            "InList",
            "VList",
            "updT",
            "UpList",
            "Attribute",
            "Relation",
            "Pattern",
            "NUMBER",
            "IDENTIFIER",
    };
}
/* JavaCC - OriginalChecksum=a98d02d014cd4a11e09e54ce0c088b87 (do not edit this line) */
